version: '2.26'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p0stgreS
      POSTGRES_DB: invest
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  app:
    build: .
    environment:
      CONFIG_PATH: /app/config.json
      HTML_TEMPLATE_PATH: /app/ui/html/
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: p0stgreS
      DB_NAME: invest
      DB_SSLMODE: disable
    depends_on:
      - db
    ports:
      - "80:80"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
